---
# https://argo-cd.readthedocs.io/en/stable/user-guide/projects/
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - 'https://github.com/the-technat/axiom.git'
  destinations:
  - namespace: '*'
    server: '*'
---
# https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/the-technat/axiom.git
      revision: HEAD
      directories:
      - path: argocd/core/*
  template:
    metadata:
      name: '{{ `{{.path.basename}}` }}'
      annotations:
        argocd.argoproj.io/sync-wave: "-3"
    spec:
      project: "core"
      source:
        repoURL: https://github.com/the-technat/axiom.git
        targetRevision: HEAD
        path: '{{ `{{.path.path}}` }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ `{{.path.basename}}` }}'
      syncPolicy:
        automated:
          prune: true 
          selfHeal: true 
          allowEmpty: false 
        syncOptions:
        - ServerSideApply=true
