---
# https://argo-cd.readthedocs.io/en/stable/user-guide/projects/
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - 'https://github.com/the-technat/axiom.git'
  destinations:
  - namespace: '*'
    server: '*'
---
# https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-Git/
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-addons
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/the-technat/axiom.git
      revision: HEAD
      directories:
      - path: argocd/infrastructure/*
  template:
    metadata:
      name: '{{.path.basename}}'
      labels:
        argocd.argoproj.io/sync-wave: "-2"
    spec:
      project: "infra"
      source:
        repoURL: https://github.com/the-technat/axiom.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        automated:
          prune: true 
          selfHeal: true 
          allowEmpty: false 
        syncOptions:
        - ServerSideApply=true
