# apiVersion: external-secrets.io/v1beta1
# kind: ExternalSecret
# metadata:
#   name: akeyless-argocd-github-oauth
#   annotations:
#     argocd.argoproj.io/hook: PreSync
# spec:
#   refreshInterval: 1h
#   secretStoreRef:
#     kind: ClusterSecretStore
#     name: akeyless-core
#   target:
#     name: github-oidc
#     creationPolicy: Owner
#   data:
#     - secretKey: client_secret
#       remoteRef:
#         key: /axiom/l-t/argocd/github-oauth-client-secret
#     - secretKey: client_id
#       remoteRef:
#         key: /axiom/l-t/argocd/github-oauth-client-id