apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: akeyless-cert-manager-hetzner-dns
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-core
  target:
    name: hetzner-dns-token
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: /axiom/core/cert-manager/hetzner-dns-token
