apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: akeyless-cert-manager-infomaniak-dns
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-core
  target:
    name: infomaniak-api-credentials
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: /axiom/core/cert-manager/infomaniak-dns-token
