# https://github.com/Infomaniak/cert-manager-webhook-infomaniak
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infomaniak-webhook
  labels:
    app.kubernetes.io/name: infomaniak-webhook
---
# Grant cert-manager permission to validate using our apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infomaniak-webhook:domain-solver
  labels:
    app.kubernetes.io/name: infomaniak-webhook
rules:
  - apiGroups:
      - acme.infomaniak.com
    resources:
      - '*'
    verbs:
      - 'create'
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infomaniak-webhook:auth-delegator
  labels:
    app.kubernetes.io/name: infomaniak-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: infomaniak-webhook
    namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infomaniak-webhook:domain-solver
  labels:
    app.kubernetes.io/name: infomaniak-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infomaniak-webhook:domain-solver
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
# Role to access infomaniak-webhook secrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: infomaniak-webhook:secret-reader
  labels:
    app.kubernetes.io/name: infomaniak-webhook
rules:
  - apiGroups: [""]
    resources:
      - 'secrets'
    resourceNames: [infomaniak-api-credentials]
    verbs:
      - 'get'
      - 'watch'
      - 'list'
# Allow infomaniak-webhook ServiceAccount to read its secrets
---
# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: infomaniak-webhook:webhook-authentication-reader
#   namespace: kube-system
#   labels:
#     app.kubernetes.io/name: infomaniak-webhook
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: extension-apiserver-authentication-reader
# subjects:
#   - apiGroup: ""
#     kind: ServiceAccount
#     name: infomaniak-webhook
#     namespace: cert-manager
---
# Source: infomaniak-webhook/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infomaniak-webhook:secret-reader
  labels:
    app.kubernetes.io/name: infomaniak-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infomaniak-webhook:secret-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: infomaniak-webhook
    namespace: cert-manager
---
# Source: infomaniak-webhook/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: infomaniak-webhook
  labels:
    app.kubernetes.io/name: infomaniak-webhook
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: infomaniak-webhook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infomaniak-webhook
  labels:
    app.kubernetes.io/name: infomaniak-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: infomaniak-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: infomaniak-webhook
    spec:
      serviceAccountName: infomaniak-webhook
      containers:
        - name: infomaniak-webhook
          image: "ghcr.io/infomaniak/cert-manager-webhook-infomaniak:latest"
          imagePullPolicy: IfNotPresent
          args:
            - --v=2
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          env:
            - name: GROUP_NAME
              value: "acme.infomaniak.com"
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /healthz
              port: https
          volumeMounts:
            - name: certs
              mountPath: /tls
              readOnly: true
          resources:
            {}
      volumes:
        - name: certs
          secret:
            secretName: infomaniak-webhook-webhook-tls
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.acme.infomaniak.com
  labels:
    app.kubernetes.io/name: infomaniak-webhook
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/infomaniak-webhook-webhook-tls"
spec:
  group: acme.infomaniak.com
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: infomaniak-webhook
    namespace: cert-manager-infomaniak
  version: v1alpha1
---
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infomaniak-webhook-ca
  labels:
    app.kubernetes.io/name: infomaniak-webhook
spec:
  secretName: infomaniak-webhook-ca
  duration: 43800h # 5y
  issuerRef:
    name: infomaniak-webhook-selfsign
  commonName: "ca.infomaniak-webhook.cert-manager"
  isCA: true
---
# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infomaniak-webhook-webhook-tls
  labels:
    app.kubernetes.io/name: infomaniak-webhook
spec:
  secretName: infomaniak-webhook-webhook-tls
  duration: 8760h # 1y
  issuerRef:
    name: infomaniak-webhook-ca
  dnsNames:
  - infomaniak-webhook
  - infomaniak-webhook.cert-manager-infomaniak
  - infomaniak-webhook.cert-manager-infomaniak.svc
---
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: infomaniak-webhook-selfsign
  labels:
    app.kubernetes.io/name: infomaniak-webhook
spec:
  selfSigned: {}
---
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: infomaniak-webhook-ca
  labels:
    app.kubernetes.io/name: infomaniak-webhook
spec:
  ca:
    secretName: infomaniak-webhook-ca
