apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-dns-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: root@technat.ch
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: cilium