apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-dns-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: root@technat.ch
    privateKeySecretRef:
      name: letsencrypt-production-dns-account
    solvers:
      - dns01:
          webhook:
            groupName: acme.axiom.technat.ch
            solverName: hetzner
            config:
              secretName: hetzner-dns-token
              apiUrl: https://dns.hetzner.com/api/v1