apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-dns-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: root@technat.ch
    privateKeySecretRef:
      name: le-dns-production
    solvers:
      - dns01:
          webhook:
            groupName: acme.infomaniak.com
            solverName: infomaniak
            config:
              apiTokenSecretRef:
                name: infomaniak-api-credentails
                key: api-token