# Grant the webhook permission to read the ConfigMap containing the Kubernetes
# apiserver's requestheader-ca-certificate.
# This ConfigMap is automatically created by the Kubernetes apiserver.
# apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: infomaniak-webhook:webhook-authentication-reader
  namespace: kube-system
  labels:
    app.kubernetes.io/name: infomaniak-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: infomaniak-webhook
    namespace: cert-manager