apiVersion: external-secrets.io/v2beta1
kind: ExternalSecret
metadata:
  name: akeyless-smb-csi-creds
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  refreshInterval: 2h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-infra
  target:
    name: smb-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: /axiom/infra/csi-driver-smb/storagebox_username
    - secretKey: password
      remoteRef:
        key: /axiom/infra/csi-driver-smb/storagebox_password