---
- name: Grab information about services
  ansible.builtin.service_facts:
  changed_when: false
- name: Display all variables/facts known for a host
  ansible.builtin.debug:
    var: ansible_facts
    verbosity: 4
- name: Create /etc/rancher/k3s directory
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: '0750'
- name: Create/update config.yaml 
  ansible.builtin.template:
    src: k3s-config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
    mode: '0750'
# # It's not declarative to do it that way, but the script is already well tested and os-agnostic
- name: Download k3s-script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    checksum: sha256:https://get.k3s.io/sha256
    dest: /root/k3s.sh
    owner: root
    group: root
    mode: '0750'
- name: Install k3s
  ansible.builtin.shell: /tmp/k3s.sh server --token "{{ lookup('hashi_vault', 'secret=secret/axiom/cluster/k3s-token' ).values() | first}}"
  register: k3s_installation
  when: ansible_facts.services['k3s.service'].status == "not-found"
# - name: K3s_install_master | restart K3s service
#   ansible.builtin.systemd:
#     name: k3s
#     state: restarted
#   when: not ansible_check_mode
# - name: K3s_install_master | replace IP of the master node in config file
#   ansible.builtin.command: kubectl config set-cluster default --server=https://{{ hostvars['k3s-master1'].ansible_host }}:6443
#   register: change_ip
#   changed_when: change_ip.rc != 0