---
- name: Grab information about services
  ansible.builtin.service_facts:
  changed_when: false
- name: Display all variables/facts known for a host
  ansible.builtin.debug:
    var: ansible_facts
    verbosity: 4
- name: Create /etc/rancher/k3s directory
  ansible.builtin.file:
    path: /etc/rancher/k3s
    state: directory
    mode: u=rw,g=r,o=r
- name: Create config.yaml if it doesn't exist
  ansible.builtin.template:
    src: k3s-config.yaml.j2
    dest: /etc/rancher/k3s/config.yaml
# # It's not declarative to do it that way, but the script is already well tested and os-agnostic
- name: Download k3s-script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    checksum: sha256:https://get.k3s.io/sha256
    dest: /root/k3s.sh
    owner: root
    group: root
    mode: 700
# - name: Install k3s
#   ansible.builtin.shell: /tmp/k3s.sh server
#   register: k3s_installation
#   when: ansible_facts.services['k3s.service'].status == "not-found"
