---
- name: Common roles
  hosts: tag_acl_axiom
  gather_facts: true
  remote_user: ansible
  become: true
  become_user: root
  vars:
    k3s_version: v1.28.2+k3s1
  roles:
    - role: prepos
    - role: download

- name: Control Plane
  hosts: tag_info_control_plane
  remote_user: ansible
  become: true
  become_user: root
  roles:
    - role: master

- name: Compute Plane
  hosts: tag_info_compute_plane
  remote_user: ansible
  become: true
  become_user: root
  # roles:
  # - role: k3s/worker
