global:
  networkPolicy:
    create: true

configs:
  params:
    server.insecure: true
  cm:
    url: "https://argocd.axiom.technat.ch"
    server.rbac.log.enforce.enable: "true"
    exec.enabled: "true"
    admin.enabled: "true"
    timeout.reconciliation: 20
    # dex.config: |
    #   connectors:
    #     - type: github
    #       id: github
    #       name: GitHub
    #       config:
    #         clientID: $github-oidc:client_id
    #         clientSecret: $github-oidc:client_secret 
    #         orgs:
    #         - name: alleaffengaffen
  rbac:
    # policy.csv: |
    #   # Grant all members of 'alleaffengaffen:orangutans' admins
    #   g, alleaffengaffen:orangutans, role:admin
    policy.default: role:readonly

server:
  ingress:
    enabled: true
    https: true
    annotations:
      cert-manager.io/cluster-issuer: le-dns-staging
      ingress.cilium.io/tls-passthrough: true
    ingressClassName: "cilium"
    hosts:
      - argocd.axiom.technat.ch
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.axiom.technat.ch
  priorityClassName: "core"
  metrics:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

controller:
  enableStatefulSet: true
  priorityClassName: "core"
  metrics:
    enabled: true
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 128Mi

notifications:
  priorityClassName: "core"
  metrics:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

redis:
  priorityClassName: "core"
  metrics:
    enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 5m
        memory: 16Mi
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi

repoServer:
  priorityClassName: "core"
  metrics:
    enabled: true
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 64Mi

applicationSet:
  priorityClassName: "core"
  metrics:
    enabled: true
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi