apiVersion: v2
name: external-secrets
version: 0.0.0
dependencies:
  - name: external-secrets
    version: 1.13.0
    repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts