csi-driver-smb:
  feature:
    enableGetVolumeStats: true

  controller:
    resources:
      csiProvisioner:
        limits:
          memory: 300Mi
        requests:
          cpu: 10m
          memory: 20Mi
      livenessProbe:
        limits:
          memory: 100Mi
        requests:
          cpu: 10m
          memory: 20Mi
      smb:
        limits:
          memory: 200Mi
        requests:
          cpu: 10m
          memory: 20Mi

  linux:
    resources:
      livenessProbe:
        limits:
          memory: 100Mi
        requests:
          cpu: 10m
          memory: 20Mi
      nodeDriverRegistrar:
        limits:
          memory: 100Mi
        requests:
          cpu: 10m
          memory: 20Mi
      smb:
        limits:
          memory: 200Mi
        requests:
          cpu: 10m
          memory: 20Mi

  priorityClassName: infra
