name: Cluster Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
    steps:
    - name: Checkout repository
      with:
        submodules: true
      uses: actions/checkout@v4
    - name: Fetch secrets from AKeyless
      id: fetch-secrets
      uses: LanceMcCarthy/akeyless-action@v3
      with:
        access-id: ${{ secrets.AKEYLESS_ACCESS_ID}}
        static-secrets: '{"/axiom/general/tailscale_oauth_client_id":"TS_OAUTH_CLIENT_ID","/axiom/general/tailscale_oauth_secret":"TS_OAUTH_SECRET"}'
    - name: Join tailnet
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ env.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ env.TS_OAUTH_SECRET }}
        tags: tag:axiom-ci
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}
    - name: Install pip dependencies
      run: pip install --upgrade --upgrade-strategy eager -r requirements.txt 
    - name: Install ansible-galaxy requirements
      run: ansible-galaxy install -r collections/requirements.yml
    - name: Run ansible playbook
      run: ansible-playbook -i ansible-tailscale-inventory/ansible-tailscale-inventory.py cluster.yml
      env: 
        ANSIBLE_CONFIG: ansible.cfg