name: Linting

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ansible:
    name: "Ansible Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Install dependencies.
        run: pip3 install -r ansible/requirements.txt
      - name: Install ansible-lint
        run: pip3 install ansible-lint
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('ansible/requirements.txt') }}
      - name: Run ansible-lint.
        run: ansible-lint -c ansible/.ansible-lint
