name: Linting

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  ansible:
    name: "Ansible Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Ansible Lint
        uses: ansible/ansible-lint@v6.20.3