
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: akeyless-pki
  namespace: cert-manager
spec:
  vault:
    path: /pki/sign/axiom/ca/primary_ca
    server: https://hvp.akeyless.io
    auth:
      appRole:
        path: approle
        roleId: "p-mef9og8p2qykam"
        secretRef:
          name: akeyless-creds
          key: secretId