apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: akeyless-infrastructure
spec:
  provider:
    akeyless:
      akeylessGWApiURL: "https://api.akeyless.io"
      authSecretRef:
        secretRef:
          accessID:
            name: akeyless-infrastructure-creds
            key: accessId
            namespace: external-secrets
          accessType:
            name: akeyless-infrastructure-creds
            key: accessType
            namespace: external-secrets
          accessTypeParam:
            name: akeyless-infrastructure-creds
            key: accessTypeParam
            namespace: external-secrets
  conditions:
  - namespaceSelector:
      matchLabels:
        axiom.technat.ch/infrastructure: "true"