k8sServiceHost: "api.axiom.technat.ch"
k8sServicePort: "6443"
annotateK8sNode: true
rollOutCiliumPods: true
kubeProxyReplacement: "strict"
ipam:
  mode: "kubernetes"
operator:
  rollOutPods: true
  replicas: 1

policyEnforcementMode: always
policyAuditMode: true
hostFirewall:
  enabled: true
